In [1]:
import numpy as np

In [2]:
import scipy.sparse

In [3]:
import pickle

In [ ]:
import xgboost as xgb

# 从文件或者 xgboost 生成的二进制缓存中读取数据

In [5]:
dtrain = xgb.DMatrix('demo/data/agaricus.txt.train')
dtest = xgb.DMatrix('demo/data/agaricus.txt.test')

# 用 dict 保存参数

In [7]:
param = {
    'max_depth': 2,
    'eta': 1,
    'silent': 1,
    'objective': 'binary:logistic'
}

# 设置 validation set 

In [8]:
watchlist = [(dtest, 'eval'), (dtrain, 'train')]

In [9]:
num_round = 2

In [10]:
bst = xgb.train(param, dtrain, num_round, watchlist)

[0]	eval-error:0.042831	train-error:0.046522
[1]	eval-error:0.021726	train-error:0.022263


# 预测

In [11]:
preds = bst.predict(dtest)

In [12]:
labels = dtest.get_label()

In [13]:
labels

array([0., 1., 0., ..., 1., 0., 1.], dtype=float32)

In [14]:
preds

array([0.28583017, 0.9239239 , 0.28583017, ..., 0.9239239 , 0.05169873,
       0.9239239 ], dtype=float32)

In [15]:
preds > 0.5

array([False,  True, False, ...,  True, False,  True])

In [23]:
pred_labels = np.copy(preds)

# 选择阈值进行二分类

In [30]:
threshold = 0.5

In [31]:
pred_labels[preds > threshold] = 1

In [32]:
pred_labels[preds <= threshold] = 0

In [33]:
pred_labels

array([0., 1., 0., ..., 1., 0., 1.], dtype=float32)

In [34]:
print(sum(pred_labels == labels) / labels.shape)

[0.97827436]


In [37]:
sum(np.array([True, False, True, False]))

2

In [38]:
bst.save_model('test.model')